version: 2

models:
  - name: int_all_crypto_historical
    description: "PK tests; Test to ensure that the cardinality of the new history table has the same cardinality as the original"
    columns:
      - name: date
        tests:
          - not_null
          - dbt_utils.cardinality_equality:
              field: date
              to: ref('stg_all_crypto_historical')
      - name: ticker
        tests:
          - not_null
          - dbt_utils.cardinality_equality:
              field: ticker
              to: ref('stg_all_crypto_historical')
    tests:
      - unique:
          column_name: "(ticker || '-' || date )"

  - name: int_all_tickers_and_dividends_historical
    description: "PK tests; Test to ensure that the cardinality of the new history table has the same cardinality as the original"
    columns:
      - name: date
        tests:
          - not_null
          - dbt_utils.cardinality_equality:
              field: date
              to: ref('stg_all_tickers_historical')
      - name: ticker
        tests:
          - not_null
          - dbt_utils.cardinality_equality:
              field: ticker
              to: ref('stg_all_tickers_historical')
    tests:
      - unique:
          column_name: "(ticker || '-' || date )"

  - name: int_all_tickers_by_quarter
    description: "Test to ensure Pks and Fks"
    columns:
      - name: ticker
        description: "A foreign key for this table"
        tests:
          - not_null
      - name: year
        description: "A foreign key for this table"
        tests:
          - not_null
      - name: quarter
        description: "A foreign key for this table"
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(ticker || '-' || year || '-' || quarter )"


  - name: int_eps_pl_by_ticker
    description: "Test to ensure Pks and Fks"
    columns:
      - name: cik
        description: "A foreign key for this table"
        tests:
          - not_null
      - name: year
        description: "A foreign key for this table"
        tests:
          - not_null
      - name: quarter
        description: "A foreign key for this table"
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(cik || '-' || year || '-' || quarter )"