
version: 2

models:
  - name: polygon_all_tickers_history_summary
    description: "A starter dbt model"
    columns:
      - name: ticker
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: polygon_all_tickers_history_summary_apple
    description: "A starter dbt model"
    columns:
      - name: ticker
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
