
version: 2

models:

  - name: all_tickers_history_summary
    description: "Add this description"
    columns:
      - name: ticker
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: all_tickers_history_summary_apple
    description: "Add this description"
    columns:
      - name: ticker
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
